### ISSUE TITLE
Methods go to (as yet unclassified)

### ISSUE THREAD

**Issue by WillHensel** [jgfoster/Jade#62] opened 2021-12-21 18:50 UTC
All new and edited methods go to a `(as yet unclassified)` category and must be recategorized.

**Comment by jgfoster** [comment] 2021-12-22 03:13
The category string seems to be added as part of GemStone's `Behavior>>compileMethod:`. The only GemStone caller to that method is part of renaming an instance variable, which seems to be an unlikely code path for this problem. Yet there are no calls to this method in Jade!

It turns out that code with a class-side override of #'doesNotUnderstand:' changed the a message by removing keyword segments until a method was found. In combination with a Jade method that sent an unrecognized message this gave us the unexpected behavior.

JadeServer64Bit3x>>compileMethod:behavior:symbolList:inCategory: should be modified to see if the selector is recognized before sending the message.

**Comment by jgfoster** [comment] 2021-12-22 04:12
Fixed in 2.4.18

**Closed as completed by jgfoster** 2021-12-22 04:12 UTC
